### ISSUE TITLE
Cannot compile zapcc with zapcc compiler

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [yrnkrn/zapcc#17]
Hello.
I compiled zapcc compiler with GCC 8.1.1 on Fedora 28. After that I am trying to compile zapcc again with already compiled zapcc compiler, but got this error:
```
Building CXX object lib/Target.../LLVMXCoreCodeGen.dir/XCoreSubtarget.cpp.o
note: when including '/home/zamazan4ik/OpenSource/zapcc/build_zapcc/lib/Target/XCore/XCoreGenRegisterInfo.inc', macro 'GET_REGINFO_TARGET_DESC' was '(defined)' before but is '(undefined)' now
```
I used build instruction from README.md 
What I missed?

**Comment by yrnkrn** [comment]
zapcc notes that due to a macro change it had to clear the cache. This is not an error, it's OK and build continues.
