### ISSUE TITLE
Add a comparison benchmark to ccache

### ISSUE THREAD

**Issue by udnaan** [yrnkrn/zapcc#2]

**Comment by yrnkrn** [comment]
ccache works completely different to zapcc so I'm not sure this is a fair comparison to either.

**Comment by udnaan** [comment]
Fair enough. Is there another tool that is more relevant for benchmark comparison?

**Comment by yrnkrn** [comment]
Precompiled headers & unity builds are closer in "spirit". Each has its limitations, though. 

See discussions on Phoronix:
https://www.phoronix.com/forums/forum/software/programming-compilers/936682-zapcc-1-0-compiler-announced
https://www.phoronix.com/forums/forum/phoronix/latest-phoronix-articles/1031070-zapcc-caching-c-compiler-open-sourced

and Ycombinator:
https://news.ycombinator.com/item?id=9592601
https://news.ycombinator.com/item?id=13044005
https://news.ycombinator.com/item?id=17332330

**Comment by udnaan** [comment]
I would think that a caching tool such as ccache would be much closer, given zapcc's own pitch as a caching tool.
In my own experience, unless if you are using a header heavy library, precompile headers don't help.

Either way, good luck with the tool. I'll keep a watch just in case.
