### ISSUE TITLE
zapcc-cl can not start the build server

### ISSUE THREAD

**Issue by permotion88** [yrnkrn/zapcc#26]
When trying to build a simple application with command:

`D:\zapcc\install_msvc_release\bin\zapcc-cl.exe Test.cpp`

I get an error

`startServer: CreateProcess 'D:\zapcc\install_msvc_release\bin\zapcc-cls.exe 1 0 0' GetLastError = 0.
connectToOne error: Unexpected error.`

If I run first the command:

`D:\zapcc\install_msvc_release\bin\zapcc.exe Test.cpp`

the server starts and using of the zapcc-cl is possible too.

If I see it right there is no application with name zapcc-cls...

**Comment by yrnkrn** [comment]
Targetting Visual C++ binaries or using `zapcc-cl` is not supported, documented in 9bd04e7618bafaf6d938b0aed5837c1c5b312645.
Your workaround will indeed work launching zapcc but will not fix the broken support for Visual C++ ABI.
