### ISSUE TITLE
installed the compiler on ubuntu linux but dosen't work

### ISSUE THREAD

**Issue by Tm24sense** [yrnkrn/zapcc#50]
I have tried installing the zapcc compiler on ubuntu 20.04 i ran all the commands specified but when i try running the tests it fails and when i try running zappc by zapcc ... and ./zapcc and zappc still wont work any help would be very helpful.

**Comment by yrnkrn** [comment]
Hi, zapcc was not tested on ubuntu 20.04, it is older.
