### ISSUE TITLE
could not install zapcc on linux ubuntu 22.04

### ISSUE THREAD

**Issue by Tm24sense** [yrnkrn/zapcc#51]
I recently left a comment about how it wasnt working but i said the ubuntu version incorrect. I followed all instructions to install the compiler but nothing works. Can you please give me the commands to install it here.  Thank you

**Comment by yrnkrn** [comment]
zapcc was not updated since 2018 and will require fixes to work with newer Ubuntu.

**Comment by Tm24sense** [comment]
when will it happen??

**Comment by yrnkrn** [comment]
This is open-source software... when someone takes the time to fix it.
