### ISSUE TITLE
How do i compile a c++ file with zapcc

### ISSUE THREAD

**Issue by Tm24sense** [yrnkrn/zapcc#52]
So i just got zapcc working i switched to arch so it can work when i type zapcc it shows error no input file like any other compiler.But when i was installing it told me that you have to delete clang or conflicts might happen. So i pressed yes after that i made a main.cpp file and made a simple for loop that prints the current value of i.When i try running it but it gives me 2 error messages.So i tried compiling  a file that has a empty main function it genarates the exuctable and i run it no problems.This problems seems to happen when i include any header files.Maybe becuase i deleted clang.If so then tell me and i will reinstall it again.I installed zapcc using yay.Any help would be greatly helpful.
Edit:
i just realized its a linker error

**Comment by yrnkrn** [comment]
Hi, you do not have to delete clang to use zapcc.
