### ISSUE TITLE
Cannot compile using mingw-w64

### ISSUE THREAD

**Issue by Mathtin** [yrnkrn/zapcc#8]
Sure, mingw-w64 support is experimental. But there are only two errors:
M_PI undefined - need to add _USE_MATH_DEFINES definition under mingw definition condition;
InitializeProcThreadAttributeList undefined - need to specify _WIN32_WINNT > 0x0600;

**Comment by yrnkrn** [comment]
Fixed in aead2bda7dc2e7459159c9a49da60dfb8ea5fcf2 and f653b2dba4cc6c5a66f032222032366132fc9785.
